start_irrigation:
  name: Start Irrigation
  description: Start irrigation for a specific zone with configurable duration.
  fields:
    device_id:
      name: Device ID
      description: The device ID (e.g., 'hub_143591' or 'device_143591_1')
      required: true
      selector:
        text:
    zone:
      name: Zone
      description: The irrigation zone number (1-3)
      required: true
      selector:
        number:
          min: 1
          max: 3
          mode: box
    duration:
      name: Duration
      description: Duration in seconds (default: 600 seconds / 10 minutes)
      required: false
      default: 600
      selector:
        number:
          min: 1
          max: 7200
          mode: box
          unit_of_measurement: seconds

stop_irrigation:
  name: Stop Irrigation
  description: Stop irrigation for a specific zone.
  fields:
    device_id:
      name: Device ID
      description: The device ID (e.g., 'hub_143591' or 'device_143591_1')
      required: true
      selector:
        text:
    zone:
      name: Zone
      description: The irrigation zone number (1-3)
      required: true
      selector:
        number:
          min: 1
          max: 3
          mode: box